---
title: "Инструкция"
date: "Дата последнего обновления: 2021-03-14"
output:
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Что такое ClinRTools?

ClinRTools - это набор приложений для планирования клинических исследований.

Демонстрационная версия содержит ограниченное число приложений.

**Данный демонстрационный набор распространяется без какой-либо гарантии и должен использоваться на свой страх и риск.**

Пожалуйста, обращайтесь к ответственному биостатистику для проверки и валидации расчетов.

### Техническая информация

Все расчеты в ClinRTools производятся с использованием статистического пакета R.

Запуск приложения происходит на сервере, поэтому пользователям не нужно устанавливать R на рабочий компьютер.

Код для воспроизведения расчетов, а также системную версию R можно получить непосредственно в приложении.

### Помощь и обратная связь

Демонстрационная версия распространяется ClinRTools распространяется без какой-либо официальной поддержки.

Все возникающие вопросы, пожелания и обратную связь можно направлять автору приложения [в сети LinkedIn](https://www.linkedin.com/in/parsadanyan/){target="_blank"} либо по электронной почте: eduard@stats-consult.com

